[package]
name = "area"
version = "0.1.0"
authors = ["练志朋 <huihuisky@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
